apiVersion: v1
kind: Service
metadata:
  name: abc-company-service
spec:
  type: NodePort
  selector:
    app: abc-company
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081